Feat/about
sopt-makers/sopt.org-backend pull request #46
Opened 2023-04-22 06:49 UTC by Tjdnjs

### 관련 이슈가 있다면 적어주세요.
개발한 Entity가 DB에 반영되지 않는데 typeorm 관련 명령어가 Package.json에 없는 것 같습니다 ! 마이그레이션이 아닌 다른 방법을 사용하고 있는 걸까요 ... ?

## 📌 개발 이유

about sopt 탭 개설

## 💻 수정 사항

entity 개발 및 관련하여 기본적인 controller, service 틀 작성

## 🎯 리뷰 포인트

entity 수정사항 및 comment 추가 / DB에 마이그레이션이 되지 않는 점

2023-04-23 01:54 UTC, dudgns3tp requested changes

2023-04-23 01:54 UTC, dudgns3tp commented on src/aboutsopt/entities/aboutsopt.entity.ts
> +  @PrimaryGeneratedColumn({ type: 'integer', name: 'id', comment: '기수' })
기수 상태는  AutoIncrement 옵션이 제거된  @PrimaryColumn을 사용하는게 더 맞지 않을까요?!

2023-04-23 01:54 UTC, dudgns3tp commented on src/aboutsopt/entities/aboutsopt.entity.ts
> +  plan_curriculum: string;
스네이크 케이스를 모두 카멜케이스로 수정 해주세요!  (컨벤션)
core_description,  desiggn_curriculum.. 등등

2023-04-23 01:54 UTC, dudgns3tp commented on src/aboutsopt/entities/aboutsopt.entity.ts
> +  @Column('varchar', { name: 'android', nullable: true, length: 400, comment: '안드로이드 파트 커리큘럼' })
데이터베이스 name과 엔티티 프러퍼티 명이 일치하지 않습니다. 
통일을 시키던가, name option을 제거하시면 될 것 같습니다!

2023-04-23 01:54 UTC, dudgns3tp commented on src/aboutsopt/entities/activity.entity.ts
> +  aboutsopt: AboutSopt;
aboutSopt!

2023-04-23 02:03 UTC, dudgns3tp commented
보통은 개발 stage에선 synchronize:true 옵션을 사용하고, production stage에선 typeorm 마이그레이션을 사용하던가, 직접 짜던가 이게 관례인것 같아요. ( 또는 synchronize:true를 아예 사용하지 않던가)

typeOrm은 저희 Package.json에 존재 합니다.. ! 

개발 단계이니 TypeOrmModule을 설정하는 곳에서 synchronize:true 옵션만 활성화 해서 sync 해보시겠어요?!

2023-04-23 02:06 UTC, dudgns3tp commented
또한 컨트롤러가 지금 엔티티마다 존재하는데 저희 AboutTab 요구사항에선 컨트롤러가 세개나 있을 필요가 없어보여요.
혹시 이렇게 만든 이유가 따로 있을까요?!

2023-04-23 02:45 UTC, Tjdnjs commented
> 또한 컨트롤러가 지금 엔티티마다 존재하는데 저희 AboutTab 요구사항에선 컨트롤러가 세개나 있을 필요가 없어보여요. 혹시 이렇게 만든 이유가 따로 있을까요?!
> 
> 좀 더 부연설명을 하자면, 어드민 페이지에서 AboutSopt, Activity, CoreValue 를 생성하거나, 수정할때 이 세개의 영역들의 생성, 수정,삭제되는 라이플 사이클이 독립적이지 않고, 모두 한번에 생성, 수정, 삭제가 되는데 Controller를 찢어놔서 각각 의 작업을 해야할 필요가 있는가 라는 의견입니다! ( 조회도 마찬가지..!)

aboutsopt 컨트롤러에 조회 기능을 넣고, (조회는 한 번에 !)
activity와 corevalue 컨트롤러에는 해당 값을 post 하는 기능을 넣으려 했어요 ! activity, corevalue 테이블에 값을 삽입하고, 해당 값들을 aboutsopt 조회 시 join해서 가져온다고 생각해서 컨트롤러를 3개 만들어두었습니다. 

서비스에 Injectrepository를 3개 달아서 컨트롤러도 한 파일로 합치는 게 나을까요 ??

2023-04-24 00:31 UTC, dudgns3tp commented on src/aboutsopt/entities/aboutsopt.entity.ts
> +  thumbnail: string;
이것도 BannerImage로 변경하는게 어떨까?

2023-04-24 00:31 UTC, dudgns3tp commented on src/aboutsopt/entities/activity.entity.ts
> +
category도 필요할것 같아!  (enum으로)

2023-04-26 06:49 UTC, dudgns3tp requested changes

2023-04-27 04:26 UTC, merged